### ISSUE TITLE
클래스 관련 자바 파일 분리 

### ISSUE THREAD

**Issue by wltn716** [shinah/swEngineering#1]
한 자바파일에 main함수 포함한 클래스와 그 외 클래스들 모두 작성하는 것 보다,
각각 기능별로 분리해서 여러개의 자바파일에 작성하는게 좋을 것 같은데 어떻게 생각하시나요!

**Comment by shinah** [comment]
오..네! 기능을 분리 해서 자바파일 만드는게 좋은 아이디어 인거 같습니다

**Comment by linibell** [comment]
좋아요! 분리해서 작성해요:)
